/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react-hooks/exhaustive-deps */
"use client";

import { useState, useEffect, useRef } from "react";
import {
  Upload,
  RotateCcw,
  FileJson,
  BookOpen,
  ChevronRight,
  Sparkles,
  Clipboard,
  Check,
  Download,
  List,
  Code,
} from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";
import JsonEditor from "@/components/JsonEditor";
import PackList from "@/components/PackList";
import AiPanel from "@/components/AiPanel";
import CustomDropdown from "@/components/CustomDropdown";
import { generateUUID, PackEntry, mergePacks } from "@/lib/utils";
import { formatJson } from "@/lib/prettier";
import { parsePackFile } from "@/lib/jszip";

export default function Home() {
  // Navigation
  const [activeTab, setActiveTab] = useState<
    "behavior" | "resource" | "manifest"
  >("behavior");

  // Input view tabs
  const [inputTab, setInputTab] = useState<"upload" | "manual">("upload");

  // Right workspace tabs
  const [workspaceTab, setWorkspaceTab] = useState<"editor" | "ai" | "diff">(
    "editor",
  );

  // Pack Lists
  const [behaviorPacks, setBehaviorPacks] = useState<PackEntry[]>([]);
  const [resourcePacks, setResourcePacks] = useState<PackEntry[]>([]);

  // Editor states
  const [editorValue, setEditorValue] = useState("[]");
  const [isValidJson, setIsValidJson] = useState(true);

  // Manual Input State
  const [manualUuid, setManualUuid] = useState("");
  const [manualVersion, setManualVersion] = useState("1.0.0");
  const [manualName, setManualName] = useState("");

  // Manifest Generator State
  const [manifestName, setManifestName] = useState("My Custom Pack");
  const [manifestDesc, setManifestDesc] = useState("Generated by BDSPack");
  const [manifestType, setManifestType] = useState<"behavior" | "resource">(
    "behavior",
  );
  const [manifestUuid, setManifestUuid] = useState(() => generateUUID());
  const [manifestModuleUuid, setManifestModuleUuid] = useState(() =>
    generateUUID(),
  );
  const [manifestVersionStr, setManifestVersionStr] = useState("1.0.0");
  const [minEngineVersion, setMinEngineVersion] = useState("1.20.0");

  // File Upload states
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [uploadSuccess, setUploadSuccess] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Copy & Download states
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(false);

  // Helper to parse "1.2.3" to [1, 2, 3]
  function parseVersion(vStr: string): [number, number, number] {
    const parts = vStr.split(".").map(Number);
    return [parts[0] || 1, parts[1] || 0, parts[2] || 0];
  }

  // Manifest generation function
  function generateManifestJson() {
    const versionArray = parseVersion(manifestVersionStr);
    const engineArray = parseVersion(minEngineVersion);
    const manifestObj = {
      format_version: 2,
      header: {
        name: manifestName,
        description: manifestDesc,
        uuid: manifestUuid || generateUUID(),
        version: versionArray,
        min_engine_version: engineArray,
      },
      modules: [
        {
          type: manifestType === "behavior" ? "data" : "resources",
          uuid: manifestModuleUuid || generateUUID(),
          version: versionArray,
        },
      ],
    };
    setEditorValue(JSON.stringify(manifestObj, null, 2));
    setIsValidJson(true);
  }

  // Load session from localStorage
  useEffect(() => {
    try {
      const savedTab = localStorage.getItem("bdspack_tab");
      const savedBps = localStorage.getItem("bdspack_behavior_packs");
      const savedRps = localStorage.getItem("bdspack_resource_packs");

      if (savedTab)
        setActiveTab(savedTab as "behavior" | "resource" | "manifest");
      if (savedBps) setBehaviorPacks(JSON.parse(savedBps));
      if (savedRps) setResourcePacks(JSON.parse(savedRps));
    } catch (e) {
      console.error("Failed to load localStorage session:", e);
    }
  }, []);

  // Save session to localStorage
  useEffect(() => {
    localStorage.setItem("bdspack_tab", activeTab);
    localStorage.setItem(
      "bdspack_behavior_packs",
      JSON.stringify(behaviorPacks),
    );
    localStorage.setItem(
      "bdspack_resource_packs",
      JSON.stringify(resourcePacks),
    );
  }, [activeTab, behaviorPacks, resourcePacks]);

  // Sync Editor Value when Tabs or Pack List changes
  useEffect(() => {
    if (activeTab === "manifest") {
      generateManifestJson();
      return;
    }

    const currentPacks =
      activeTab === "behavior" ? behaviorPacks : resourcePacks;
    const rawList = currentPacks.map((p) => ({
      pack_id: p.pack_id,
      version: p.version,
    }));

    setEditorValue(JSON.stringify(rawList, null, 2));
    setIsValidJson(true);
  }, [activeTab, behaviorPacks, resourcePacks]);

  useEffect(() => {
    if (activeTab === "manifest") {
      generateManifestJson();
    }
  }, [
    manifestName,
    manifestDesc,
    manifestType,
    manifestUuid,
    manifestModuleUuid,
    manifestVersionStr,
    minEngineVersion,
  ]);

  // Sync manual text changes in Editor back to pack lists
  const handleEditorChange = (newVal: string) => {
    setEditorValue(newVal);
    try {
      const parsed = JSON.parse(newVal);
      setIsValidJson(true);

      if (activeTab === "manifest") return;

      if (Array.isArray(parsed)) {
        const validated: PackEntry[] = parsed
          .filter(
            (item) =>
              item &&
              typeof item.pack_id === "string" &&
              Array.isArray(item.version),
          )
          .map((item) => ({
            pack_id: item.pack_id,
            version: [
              Number(item.version[0]) || 0,
              Number(item.version[1]) || 0,
              Number(item.version[2]) || 0,
            ],
            name: item.name || "Manual Pack Entry",
            isNew: false,
          }));

        if (activeTab === "behavior") {
          setBehaviorPacks(validated);
        } else {
          setResourcePacks(validated);
        }
      }
    } catch {
      setIsValidJson(false);
    }
  };

  // Format code
  const triggerPrettier = async () => {
    const formatted = await formatJson(editorValue);
    setEditorValue(formatted);
    setIsValidJson(true);
  };

  // Generate UUID for Manual Form
  const generateManualUuid = () => {
    setManualUuid(generateUUID());
  };

  // Add manually
  const handleAddManual = (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualUuid) {
      setUploadError("UUID tidak boleh kosong.");
      return;
    }
    const versionArray = parseVersion(manualVersion);
    const newEntry: PackEntry = {
      pack_id: manualUuid,
      version: versionArray,
      name: manualName || "Manual Entry",
      isNew: true,
    };

    if (activeTab === "behavior") {
      setBehaviorPacks((prev) => mergePacks(prev, [newEntry]));
    } else if (activeTab === "resource") {
      setResourcePacks((prev) => mergePacks(prev, [newEntry]));
    }

    setManualUuid("");
    setManualName("");
    setUploadSuccess("Pack entry berhasil ditambahkan.");
    setTimeout(() => setUploadSuccess(null), 3000);
  };

  // Reorder pack
  const handleReorder = (index: number, direction: "up" | "down") => {
    const packs =
      activeTab === "behavior" ? [...behaviorPacks] : [...resourcePacks];
    const targetIndex = direction === "up" ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= packs.length) return;

    const temp = packs[index];
    packs[index] = packs[targetIndex];
    packs[targetIndex] = temp;

    if (activeTab === "behavior") {
      setBehaviorPacks(packs);
    } else {
      setResourcePacks(packs);
    }
  };

  // Delete pack
  const handleDelete = (index: number) => {
    if (activeTab === "behavior") {
      setBehaviorPacks((prev) => prev.filter((_, i) => i !== index));
    } else {
      setResourcePacks((prev) => prev.filter((_, i) => i !== index));
    }
  };

  // Smart upload files: detects extension (.json vs .mcpack/.mcaddon)
  const handleSmartUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    setUploadError(null);
    setUploadSuccess(null);

    const file = files[0];
    const extension = file.name.split(".").pop()?.toLowerCase();

    // 1. If it's a JSON config file (e.g. world_behavior_packs.json)
    if (extension === "json") {
      try {
        const text = await file.text();
        const parsed = JSON.parse(text);
        if (!Array.isArray(parsed)) {
          throw new Error("File JSON konfigurasi harus berupa Array.");
        }

        const loadedPacks: PackEntry[] = parsed
          .map((item: any) => ({
            pack_id: item.pack_id || "",
            version: (Array.isArray(item.version)
              ? [
                  Number(item.version[0]) || 0,
                  Number(item.version[1]) || 0,
                  Number(item.version[2]) || 0,
                ]
              : [1, 0, 0]) as [number, number, number],
            name: item.name || `Pack (${item.pack_id?.substring(0, 8)})`,
            isNew: false,
          }))
          .filter((p) => p.pack_id);

        if (activeTab === "behavior") {
          setBehaviorPacks(loadedPacks);
        } else {
          setResourcePacks(loadedPacks);
        }

        setUploadSuccess(
          `Berhasil memuat ${loadedPacks.length} entry dari ${file.name}.`,
        );
        setTimeout(() => setUploadSuccess(null), 5000);
      } catch (err: any) {
        setUploadError(
          err.message || "Gagal menguraikan file JSON konfigurasi.",
        );
      } finally {
        if (fileInputRef.current) fileInputRef.current.value = "";
      }
      return;
    }

    // 2. If it's a ZIP / MCPack / MCAddon file
    try {
      const extracted = await parsePackFile(file);
      if (extracted.length === 0) {
        throw new Error(
          "Tidak dapat menemukan manifest.json yang valid di dalam file.",
        );
      }

      let bpsAdded = 0;
      let rpsAdded = 0;

      const newBps: PackEntry[] = [];
      const newRps: PackEntry[] = [];

      extracted.forEach((pack) => {
        const entry: PackEntry = {
          pack_id: pack.pack_id,
          version: pack.version,
          name: pack.name,
          description: pack.description,
          isNew: true,
        };

        if (pack.type === "behavior") {
          newBps.push(entry);
          bpsAdded++;
        } else if (pack.type === "resource") {
          newRps.push(entry);
          rpsAdded++;
        } else {
          if (activeTab === "behavior") {
            newBps.push(entry);
            bpsAdded++;
          } else {
            newRps.push(entry);
            rpsAdded++;
          }
        }
      });

      if (newBps.length > 0)
        setBehaviorPacks((prev) => mergePacks(prev, newBps));
      if (newRps.length > 0)
        setResourcePacks((prev) => mergePacks(prev, newRps));

      setUploadSuccess(
        `Sukses mengekstrak metadata dari ${file.name}. Ditambahkan: ${bpsAdded} BP, ${rpsAdded} RP.`,
      );
      setTimeout(() => setUploadSuccess(null), 5000);
    } catch (err: any) {
      setUploadError(err.message || "Gagal memproses file upload.");
    } finally {
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  };

  // Export handlers
  const handleCopy = async () => {
    setLoading(true);
    const formatted = await formatJson(editorValue);
    try {
      await navigator.clipboard.writeText(formatted);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy: ", err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    setLoading(true);
    const formatted = await formatJson(editorValue);
    const fileName =
      activeTab === "manifest"
        ? "manifest.json"
        : `world_${activeTab}_packs.json`;
    try {
      const blob = new Blob([formatted], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to download: ", err);
    } finally {
      setLoading(false);
    }
  };

  // Reset tab
  const resetSession = () => {
    if (confirm("Apakah Anda yakin ingin me-reset data tab ini?")) {
      if (activeTab === "behavior") {
        setBehaviorPacks([]);
      } else if (activeTab === "resource") {
        setResourcePacks([]);
      } else {
        setManifestName("My Custom Pack");
        setManifestDesc("Generated by BDSPack");
        setManifestType("behavior");
        setManifestUuid(generateUUID());
        setManifestModuleUuid(generateUUID());
        setManifestVersionStr("1.0.0");
        setMinEngineVersion("1.20.0");
      }
    }
  };

  const activePacks = activeTab === "behavior" ? behaviorPacks : resourcePacks;
  const hasNewPacks = activePacks.some((p) => p.isNew);

  return (
    <div className="flex-1 flex flex-col max-w-7xl w-full mx-auto p-4 md:p-6 space-y-6">
      {/* Header - Simple & Clean */}
      <header className="flex items-center justify-between border-b border-border pb-4">
        <div>
          <h1 className="text-xl md:text-2xl font-extrabold tracking-tight flex items-center space-x-2">
            <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent font-sans">
              BDSPack
            </span>
            <span className="text-[10px] bg-muted border border-border px-1.5 py-0.5 rounded text-foreground/75 font-mono">
              v1.0
            </span>
          </h1>
          <p className="text-xs text-foreground/50">
            Minecraft Bedrock Dedicated Server addon configuration manager.
          </p>
        </div>
        <ThemeToggle />
      </header>

      {/* Main Mode Navigation (Dropdown) & Reset */}
      <div className="border-b border-border pb-3 flex flex-col space-y-2">
        <label className="text-xs font-bold uppercase text-foreground/50 tracking-wider">
          Mode Kerja:
        </label>
        <div className="flex items-center w-full max-w-md gap-2">
          <CustomDropdown
            options={[
              { value: "behavior", label: "Behavior Packs (BP)" },
              { value: "resource", label: "Resource Packs (RP)" },
              { value: "manifest", label: "Manifest Generator" },
            ]}
            onChange={(val) =>
              setActiveTab(val as "behavior" | "resource" | "manifest")
            }
          />
          <button
            onClick={resetSession}
            className="p-2.5 bg-muted hover:bg-black/5 dark:hover:bg-white/5 border border-border rounded-xl text-foreground/75 hover:text-foreground cursor-pointer transition-colors flex items-center justify-center shrink-0"
            title="Reset Tab"
            aria-label="Reset Tab"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Layout Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* LEFT COLUMN: Inputs & Pack List (5 Cols) */}
        <div className="lg:col-span-5 space-y-5">
          {activeTab !== "manifest" ? (
            <>
              {/* Card 1: Add Addons Panel */}
              <div className="bg-muted/20 border border-border rounded-2xl overflow-hidden shadow-sm">
                {/* Panel Tab selector */}
                <div className="flex bg-muted/65 border-b border-border p-1 text-xs">
                  <button
                    onClick={() => setInputTab("upload")}
                    className={`flex-1 py-2 font-semibold rounded-lg text-center cursor-pointer transition-all ${
                      inputTab === "upload"
                        ? "bg-background text-foreground shadow-sm"
                        : "text-foreground/60 hover:text-foreground"
                    }`}
                  >
                    Upload Files
                  </button>
                  <button
                    onClick={() => setInputTab("manual")}
                    className={`flex-1 py-2 font-semibold rounded-lg text-center cursor-pointer transition-all ${
                      inputTab === "manual"
                        ? "bg-background text-foreground shadow-sm"
                        : "text-foreground/60 hover:text-foreground"
                    }`}
                  >
                    Add Manually
                  </button>
                </div>

                <div className="p-4">
                  {inputTab === "upload" ? (
                    <div className="space-y-3">
                      <button
                        onClick={() => fileInputRef.current?.click()}
                        className="w-full py-6 border-2 border-dashed border-border hover:border-primary/45 rounded-xl flex flex-col items-center justify-center bg-background/30 hover:bg-background/70 transition-all cursor-pointer"
                      >
                        <Upload className="w-8 h-8 text-primary/70 mb-2 animate-bounce" />
                        <span className="text-xs font-bold text-foreground">
                          Pilih atau Seret File
                        </span>
                        <span className="text-[10px] text-foreground/50 mt-1 max-w-[200px] text-center leading-normal">
                          Dukung{" "}
                          <code className="font-mono">world_packs.json</code>{" "}
                          untuk import, atau{" "}
                          <code className="font-mono">.mcpack</code> /{" "}
                          <code className="font-mono">.mcaddon</code> untuk
                          addon baru
                        </span>
                      </button>
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept=".json,.mcpack,.mcaddon,.zip"
                        onChange={handleSmartUpload}
                        className="hidden"
                      />
                    </div>
                  ) : (
                    <form onSubmit={handleAddManual} className="space-y-3">
                      <div className="space-y-1">
                        <label className="text-[10px] font-bold uppercase text-foreground/50">
                          Nama Addon (Opsional)
                        </label>
                        <input
                          type="text"
                          value={manualName}
                          onChange={(e) => setManualName(e.target.value)}
                          placeholder="cth: Realism BP"
                          className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                        />
                      </div>

                      <div className="grid grid-cols-3 gap-2">
                        <div className="col-span-2 space-y-1">
                          <div className="flex justify-between items-center">
                            <label className="text-[10px] font-bold uppercase text-foreground/50">
                              Pack UUID
                            </label>
                            <button
                              type="button"
                              onClick={generateManualUuid}
                              className="text-[9px] text-primary hover:underline font-bold"
                            >
                              Generate
                            </button>
                          </div>
                          <input
                            type="text"
                            value={manualUuid}
                            onChange={(e) => setManualUuid(e.target.value)}
                            placeholder="UUID v4"
                            className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 text-xs font-mono outline-none focus:ring-1 focus:ring-primary/50"
                          />
                        </div>
                        <div className="space-y-1">
                          <label className="text-[10px] font-bold uppercase text-foreground/50">
                            Versi
                          </label>
                          <input
                            type="text"
                            value={manualVersion}
                            onChange={(e) => setManualVersion(e.target.value)}
                            placeholder="1.0.0"
                            className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                          />
                        </div>
                      </div>

                      <button
                        type="submit"
                        className="w-full py-2 bg-primary text-white hover:bg-opacity-95 rounded-lg text-xs font-bold transition-all cursor-pointer shadow-md shadow-primary/20"
                      >
                        Tambah ke Daftar
                      </button>
                    </form>
                  )}

                  {/* Upload logs */}
                  {uploadSuccess && (
                    <div className="mt-3 p-2.5 bg-green-500/10 border border-green-500/20 text-green-500 rounded-lg text-xs font-medium">
                      {uploadSuccess}
                    </div>
                  )}
                  {uploadError && (
                    <div className="mt-3 p-2.5 bg-destructive/10 border border-destructive/20 text-destructive rounded-lg text-xs font-medium">
                      {uploadError}
                    </div>
                  )}
                </div>
              </div>

              {/* Card 2: Pack List (Only when there are packs in list) */}
              <div className="bg-muted/20 border border-border rounded-2xl p-4 space-y-3 shadow-sm">
                <div className="flex items-center justify-between">
                  <h3 className="font-bold text-xs uppercase tracking-wider text-foreground/60">
                    Daftar Urutan Pack ({activePacks.length})
                  </h3>
                  <span className="text-[9px] text-foreground/40 font-medium">
                    Lakukan reorder sesuai urutan prioritas BDS
                  </span>
                </div>
                <PackList
                  packs={activePacks}
                  type={activeTab}
                  onReorder={handleReorder}
                  onDelete={handleDelete}
                />
              </div>
            </>
          ) : (
            /* Manifest Settings Card (If Manifest Tab) */
            <div className="bg-muted/20 border border-border rounded-2xl p-4 space-y-4 shadow-sm">
              <h3 className="font-bold text-xs uppercase tracking-wider text-foreground/60 flex items-center space-x-1.5">
                <FileJson className="w-4 h-4 text-primary" />
                <span>Konfigurasi Manifest Baru</span>
              </h3>

              <div className="space-y-3.5 text-xs">
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <label className="text-[10px] font-bold uppercase text-foreground/50">
                      Tipe Pack
                    </label>
                    <select
                      value={manifestType}
                      onChange={(e) =>
                        setManifestType(
                          e.target.value as "behavior" | "resource",
                        )
                      }
                      className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-primary/50"
                    >
                      <option value="behavior">Behavior Pack (BP)</option>
                      <option value="resource">Resource Pack (RP)</option>
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-[10px] font-bold uppercase text-foreground/50">
                      Versi Addon
                    </label>
                    <input
                      type="text"
                      value={manifestVersionStr}
                      onChange={(e) => setManifestVersionStr(e.target.value)}
                      placeholder="1.0.0"
                      className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-primary/50"
                    />
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold uppercase text-foreground/50">
                    Nama Addon
                  </label>
                  <input
                    type="text"
                    value={manifestName}
                    onChange={(e) => setManifestName(e.target.value)}
                    placeholder="Nama addon..."
                    className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold uppercase text-foreground/50">
                    Deskripsi
                  </label>
                  <textarea
                    value={manifestDesc}
                    onChange={(e) => setManifestDesc(e.target.value)}
                    placeholder="Penjelasan addon..."
                    className="w-full h-16 bg-background border border-border rounded-lg px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-primary/50 resize-none"
                  />
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between items-center">
                    <label className="text-[10px] font-bold uppercase text-foreground/50">
                      Pack UUID
                    </label>
                    <button
                      onClick={() => setManifestUuid(generateUUID())}
                      className="text-[9px] text-primary hover:underline font-bold"
                    >
                      Acak
                    </button>
                  </div>
                  <input
                    type="text"
                    value={manifestUuid}
                    onChange={(e) => setManifestUuid(e.target.value)}
                    className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 font-mono outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between items-center">
                    <label className="text-[10px] font-bold uppercase text-foreground/50">
                      Module UUID
                    </label>
                    <button
                      onClick={() => setManifestModuleUuid(generateUUID())}
                      className="text-[9px] text-primary hover:underline font-bold"
                    >
                      Acak
                    </button>
                  </div>
                  <input
                    type="text"
                    value={manifestModuleUuid}
                    onChange={(e) => setManifestModuleUuid(e.target.value)}
                    className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 font-mono outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold uppercase text-foreground/50">
                    Min Engine Version (Minecraft)
                  </label>
                  <input
                    type="text"
                    value={minEngineVersion}
                    onChange={(e) => setMinEngineVersion(e.target.value)}
                    placeholder="1.20.0"
                    className="w-full bg-background border border-border rounded-lg px-2.5 py-1.5 outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* RIGHT COLUMN: Unified Workspace Card (7 Cols) */}
        <div className="lg:col-span-7 bg-muted/20 border border-border rounded-2xl overflow-hidden shadow-sm flex flex-col">
          {/* Workspace Tabs */}
          <div className="flex bg-muted/65 border-b border-border p-1 text-xs">
            <button
              onClick={() => setWorkspaceTab("editor")}
              className={`flex-1 py-2 font-semibold rounded-lg flex items-center justify-center space-x-1 cursor-pointer transition-all ${
                workspaceTab === "editor"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-foreground/60 hover:text-foreground"
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>Editor & Export</span>
            </button>
            <button
              onClick={() => setWorkspaceTab("ai")}
              className={`flex-1 py-2 font-semibold rounded-lg flex items-center justify-center space-x-1 cursor-pointer transition-all ${
                workspaceTab === "ai"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-foreground/60 hover:text-foreground"
              }`}
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>AI Assistant</span>
            </button>
            {activeTab !== "manifest" && hasNewPacks && (
              <button
                onClick={() => setWorkspaceTab("diff")}
                className={`flex-1 py-2 font-semibold rounded-lg flex items-center justify-center space-x-1 cursor-pointer transition-all ${
                  workspaceTab === "diff"
                    ? "bg-background text-foreground shadow-sm"
                    : "text-foreground/60 hover:text-foreground"
                }`}
              >
                <List className="w-3.5 h-3.5" />
                <span>Diff Summary</span>
              </button>
            )}
          </div>

          <div className="p-4 space-y-4">
            {workspaceTab === "editor" && (
              <div className="space-y-4 flex flex-col">
                {/* Code Editor section */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-[10px] font-bold uppercase tracking-wider text-foreground/50">
                    <span>
                      {activeTab === "manifest"
                        ? "manifest.json"
                        : `world_${activeTab}_packs.json`}
                    </span>
                    <span>Editor Real-time</span>
                  </div>

                  <JsonEditor
                    value={editorValue}
                    onChange={handleEditorChange}
                    isValid={isValidJson}
                    onFormat={triggerPrettier}
                    onGenerateUUID={
                      activeTab === "manifest"
                        ? () => {
                            setManifestUuid(generateUUID());
                            setManifestModuleUuid(generateUUID());
                          }
                        : undefined
                    }
                  />
                </div>

                {/* Exporter (Inline OutputPanel replacement) */}
                <div className="border border-border bg-background rounded-xl p-3.5 flex items-center justify-between text-xs">
                  <div className="flex flex-col min-w-0 mr-4">
                    <span className="text-[10px] text-foreground/50 font-bold uppercase">
                      Siap diexport
                    </span>
                    <span className="font-bold font-mono truncate text-primary">
                      {activeTab === "manifest"
                        ? "manifest.json"
                        : `world_${activeTab}_packs.json`}
                    </span>
                  </div>

                  <div className="flex items-center space-x-2">
                    <button
                      onClick={handleCopy}
                      disabled={loading || !editorValue}
                      className="p-2 bg-muted hover:bg-black/5 dark:hover:bg-white/5 rounded-lg border border-border cursor-pointer transition-colors"
                      title="Copy to Clipboard"
                    >
                      {copied ? (
                        <Check className="w-4 h-4 text-green-500" />
                      ) : (
                        <Clipboard className="w-4 h-4" />
                      )}
                    </button>

                    <button
                      onClick={handleDownload}
                      disabled={loading || !editorValue}
                      className="flex items-center space-x-1.5 py-2 px-3.5 bg-primary text-white hover:bg-opacity-95 rounded-lg font-bold transition-all shadow-md shadow-primary/20 cursor-pointer"
                    >
                      <Download className="w-4 h-4" />
                      <span>Download File</span>
                    </button>
                  </div>
                </div>
              </div>
            )}

            {workspaceTab === "ai" && (
              <AiPanel
                currentJson={editorValue}
                onAiResponse={handleEditorChange}
              />
            )}

            {workspaceTab === "diff" && activeTab !== "manifest" && (
              <div className="space-y-3.5 text-xs">
                <h4 className="font-bold uppercase tracking-wider text-foreground/60 border-b border-border pb-1.5">
                  Daftar Tambahan Pack (Diff)
                </h4>
                <div className="space-y-2 max-h-[350px] overflow-y-auto pr-1">
                  {activePacks.map((pack, idx) => (
                    <div
                      key={idx}
                      className={`p-3 rounded-xl border flex items-center justify-between transition-all ${
                        pack.isNew
                          ? "bg-green-500/5 dark:bg-green-500/10 border-green-500/30 text-green-600 dark:text-green-400 font-semibold"
                          : "bg-muted/30 border-border text-foreground/75"
                      }`}
                    >
                      <div className="truncate flex-1 min-w-0 mr-4">
                        <div className="font-bold truncate">
                          {pack.name || "Unnamed Pack"}
                        </div>
                        <div className="font-mono text-[10px] opacity-60 truncate mt-0.5">
                          {pack.pack_id}
                        </div>
                      </div>
                      <div
                        className={`text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded ${
                          pack.isNew
                            ? "bg-green-500/10 text-green-500 border border-green-500/20"
                            : "bg-black/5 dark:bg-white/5 text-foreground/50"
                        }`}
                      >
                        {pack.isNew ? "+ Added" : "Unchanged"}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* BDS Guide / Info Footer */}
      <footer className="border-t border-border pt-6 pb-8 space-y-4 text-xs">
        <div className="bg-muted/10 border border-border p-4 rounded-xl space-y-2.5">
          <h4 className="font-bold flex items-center space-x-1.5 text-foreground/80">
            <BookOpen className="w-4.5 h-4.5 text-primary" />
            <span>Panduan Instalasi Addon Bedrock Dedicated Server (BDS)</span>
          </h4>
          <p className="text-foreground/60 leading-relaxed">
            Minecraft Bedrock Dedicated Server menggunakan file JSON untuk
            mengidentifikasi addon mana yang aktif di dunia game server Anda.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>1</span>
                <ChevronRight className="w-3 h-3" />
                <span>Upload Packs</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Copy folder behavior pack ke{" "}
                <code className="font-mono">/behavior_packs</code> dan resource
                pack ke <code className="font-mono">/resource_packs</code> di
                root folder BDS Anda.
              </p>
            </div>
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>2</span>
                <ChevronRight className="w-3 h-3" />
                <span>Generate JSON</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Gunakan BDSPack untuk me-list dan mengurutkan UUID & Versi pack
                Anda, lalu download file konfigurasinya.
              </p>
            </div>
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>3</span>
                <ChevronRight className="w-3 h-3" />
                <span>Copy ke World</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Letakkan file{" "}
                <code className="font-mono">world_behavior_packs.json</code> dan{" "}
                <code className="font-mono">world_resource_packs.json</code> di
                dalam folder level dunia Anda (cth:{" "}
                <code className="font-mono">/worlds/Bedrock level/</code>).
              </p>
            </div>
          </div>
        </div>

        <div className="text-center text-foreground/40 text-[10px]">
          BDSPack &copy; 2026. Minecraft Bedrock Dedicated Server Pack
          Configuration Utility.
        </div>
      </footer>
    </div>
  );
}
