/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react-hooks/exhaustive-deps */
'use client';

import { useState, useEffect, useRef } from 'react';
import { 
  Upload, 
  Plus, 
  RotateCcw, 
  FileJson, 
  BookOpen, 
  ChevronRight
} from 'lucide-react';
import ThemeToggle from '@/components/ThemeToggle';
import ModeToggle from '@/components/ModeToggle';
import JsonEditor from '@/components/JsonEditor';
import PackList from '@/components/PackList';
import AiPanel from '@/components/AiPanel';
import OutputPanel from '@/components/OutputPanel';
import { generateUUID, PackEntry, mergePacks } from '@/lib/utils';
import { formatJson } from '@/lib/prettier';
import { parsePackFile } from '@/lib/jszip';

export default function Home() {
  // Modes & Tabs
  const [mode, setMode] = useState<'A' | 'B'>('A');
  const [activeTab, setActiveTab] = useState<'behavior' | 'resource' | 'manifest'>('behavior');

  // Pack Lists
  const [behaviorPacks, setBehaviorPacks] = useState<PackEntry[]>([]);
  const [resourcePacks, setResourcePacks] = useState<PackEntry[]>([]);

  // Editor states
  const [editorValue, setEditorValue] = useState('[]');
  const [isValidJson, setIsValidJson] = useState(true);

  // Manual Input State
  const [manualUuid, setManualUuid] = useState('');
  const [manualVersion, setManualVersion] = useState('1.0.0');
  const [manualName, setManualName] = useState('');

  // Manifest Generator State - initialized lazily to avoid useEffect setState synchronously
  const [manifestName, setManifestName] = useState('My Custom Pack');
  const [manifestDesc, setManifestDesc] = useState('Generated by BDSPack');
  const [manifestType, setManifestType] = useState<'behavior' | 'resource'>('behavior');
  const [manifestUuid, setManifestUuid] = useState(() => generateUUID());
  const [manifestModuleUuid, setManifestModuleUuid] = useState(() => generateUUID());
  const [manifestVersionStr, setManifestVersionStr] = useState('1.0.0');
  const [minEngineVersion, setMinEngineVersion] = useState('1.20.0');

  // File Upload states
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [uploadSuccess, setUploadSuccess] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const jsonFileInputRef = useRef<HTMLInputElement>(null);

  // Helper to parse "1.2.3" to [1, 2, 3] (hoisted function declaration)
  function parseVersion(vStr: string): [number, number, number] {
    const parts = vStr.split('.').map(Number);
    return [parts[0] || 1, parts[1] || 0, parts[2] || 0];
  }

  // Manifest generation function (hoisted function declaration)
  function generateManifestJson() {
    const versionArray = parseVersion(manifestVersionStr);
    const engineArray = parseVersion(minEngineVersion);
    const manifestObj = {
      format_version: 2,
      header: {
        name: manifestName,
        description: manifestDesc,
        uuid: manifestUuid || generateUUID(),
        version: versionArray,
        min_engine_version: engineArray
      },
      modules: [
        {
          type: manifestType === 'behavior' ? 'data' : 'resources',
          uuid: manifestModuleUuid || generateUUID(),
          version: versionArray
        }
      ]
    };
    setEditorValue(JSON.stringify(manifestObj, null, 2));
    setIsValidJson(true);
  }

  // Load session from localStorage
  useEffect(() => {
    try {
      const savedMode = localStorage.getItem('bdspack_mode');
      const savedTab = localStorage.getItem('bdspack_tab');
      const savedBps = localStorage.getItem('bdspack_behavior_packs');
      const savedRps = localStorage.getItem('bdspack_resource_packs');

      if (savedMode) setMode(savedMode as 'A' | 'B');
      if (savedTab) setActiveTab(savedTab as 'behavior' | 'resource' | 'manifest');
      if (savedBps) setBehaviorPacks(JSON.parse(savedBps));
      if (savedRps) setResourcePacks(JSON.parse(savedRps));
    } catch (e) {
      console.error('Failed to load localStorage session:', e);
    }
  }, []);

  // Save session to localStorage
  useEffect(() => {
    localStorage.setItem('bdspack_mode', mode);
    localStorage.setItem('bdspack_tab', activeTab);
    localStorage.setItem('bdspack_behavior_packs', JSON.stringify(behaviorPacks));
    localStorage.setItem('bdspack_resource_packs', JSON.stringify(resourcePacks));
  }, [mode, activeTab, behaviorPacks, resourcePacks]);

  // Sync Editor Value when Tabs or Pack List changes
  useEffect(() => {
    if (activeTab === 'manifest') {
      generateManifestJson();
      return;
    }

    const currentPacks = activeTab === 'behavior' ? behaviorPacks : resourcePacks;
    // Format JSON array with basic formatting for view
    const rawList = currentPacks.map(p => ({
      pack_id: p.pack_id,
      version: p.version
    }));
    
    setEditorValue(JSON.stringify(rawList, null, 2));
    setIsValidJson(true);
  }, [activeTab, behaviorPacks, resourcePacks]);

  useEffect(() => {
    if (activeTab === 'manifest') {
      generateManifestJson();
    }
  }, [manifestName, manifestDesc, manifestType, manifestUuid, manifestModuleUuid, manifestVersionStr, minEngineVersion]);

  // Sync manual text changes in Editor back to pack lists
  const handleEditorChange = (newVal: string) => {
    setEditorValue(newVal);
    try {
      const parsed = JSON.parse(newVal);
      setIsValidJson(true);

      if (activeTab === 'manifest') return; // Handled separately

      if (Array.isArray(parsed)) {
        // Validate each item
        const validated: PackEntry[] = parsed
          .filter(item => item && typeof item.pack_id === 'string' && Array.isArray(item.version))
          .map(item => ({
            pack_id: item.pack_id,
            version: [
              Number(item.version[0]) || 0,
              Number(item.version[1]) || 0,
              Number(item.version[2]) || 0
            ],
            name: item.name || 'Manual Pack Entry',
            isNew: false
          }));

        if (activeTab === 'behavior') {
          setBehaviorPacks(validated);
        } else {
          setResourcePacks(validated);
        }
      }
    } catch {
      setIsValidJson(false);
    }
  };

  // Prettier formatter handler for manual editor click
  const triggerPrettier = async () => {
    const formatted = await formatJson(editorValue);
    setEditorValue(formatted);
    setIsValidJson(true);
  };

  // Generate UUID for Manual Add Form
  const generateManualUuid = () => {
    setManualUuid(generateUUID());
  };

  // Add Pack Entry Manually
  const handleAddManual = (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualUuid) {
      setUploadError('UUID tidak boleh kosong.');
      return;
    }
    const versionArray = parseVersion(manualVersion);
    const newEntry: PackEntry = {
      pack_id: manualUuid,
      version: versionArray,
      name: manualName || 'Manual Entry',
      isNew: true
    };

    if (activeTab === 'behavior') {
      setBehaviorPacks(prev => mergePacks(prev, [newEntry]));
    } else if (activeTab === 'resource') {
      setResourcePacks(prev => mergePacks(prev, [newEntry]));
    }

    setManualUuid('');
    setManualName('');
    setUploadSuccess('Pack entry berhasil ditambahkan.');
    setTimeout(() => setUploadSuccess(null), 3000);
  };

  // Reorder pack logic
  const handleReorder = (index: number, direction: 'up' | 'down') => {
    const packs = activeTab === 'behavior' ? [...behaviorPacks] : [...resourcePacks];
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= packs.length) return;

    // Swap
    const temp = packs[index];
    packs[index] = packs[targetIndex];
    packs[targetIndex] = temp;

    if (activeTab === 'behavior') {
      setBehaviorPacks(packs);
    } else {
      setResourcePacks(packs);
    }
  };

  // Delete pack logic
  const handleDelete = (index: number) => {
    if (activeTab === 'behavior') {
      setBehaviorPacks(prev => prev.filter((_, i) => i !== index));
    } else {
      setResourcePacks(prev => prev.filter((_, i) => i !== index));
    }
  };

  // Handle uploaded .mcpack / .mcaddon
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    setUploadError(null);
    setUploadSuccess(null);

    const file = files[0];
    try {
      const extracted = await parsePackFile(file);
      if (extracted.length === 0) {
        throw new Error('Tidak dapat menemukan manifest.json yang valid di dalam file.');
      }

      let bpsAdded = 0;
      let rpsAdded = 0;

      const newBps: PackEntry[] = [];
      const newRps: PackEntry[] = [];

      extracted.forEach(pack => {
        const entry: PackEntry = {
          pack_id: pack.pack_id,
          version: pack.version,
          name: pack.name,
          description: pack.description,
          isNew: true
        };

        if (pack.type === 'behavior') {
          newBps.push(entry);
          bpsAdded++;
        } else if (pack.type === 'resource') {
          newRps.push(entry);
          rpsAdded++;
        } else {
          // If unknown, add to active tab
          if (activeTab === 'behavior') {
            newBps.push(entry);
            bpsAdded++;
          } else {
            newRps.push(entry);
            rpsAdded++;
          }
        }
      });

      if (newBps.length > 0) setBehaviorPacks(prev => mergePacks(prev, newBps));
      if (newRps.length > 0) setResourcePacks(prev => mergePacks(prev, newRps));

      setUploadSuccess(`Sukses mengekstrak metadata dari ${file.name}. Terdeteksi: ${bpsAdded} BP, ${rpsAdded} RP.`);
      setTimeout(() => setUploadSuccess(null), 5000);
    } catch (err: any) {
      setUploadError(err.message || 'Gagal memproses file upload.');
    } finally {
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  // Mode B: Upload existing JSON file
  const handleJsonUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    setUploadError(null);
    setUploadSuccess(null);

    const file = files[0];
    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      if (!Array.isArray(parsed)) {
        throw new Error('File JSON harus berupa Array dari pack config.');
      }

      const loadedPacks: PackEntry[] = parsed.map((item: any) => ({
        pack_id: item.pack_id || '',
        version: (Array.isArray(item.version)
          ? [Number(item.version[0]) || 0, Number(item.version[1]) || 0, Number(item.version[2]) || 0]
          : [1, 0, 0]) as [number, number, number],
        name: item.name || `Existing Pack (${item.pack_id?.substring(0, 8)})`,
        isNew: false
      })).filter(p => p.pack_id);

      if (activeTab === 'behavior') {
        setBehaviorPacks(loadedPacks);
      } else {
        setResourcePacks(loadedPacks);
      }

      setUploadSuccess(`Berhasil memuat ${loadedPacks.length} entry dari ${file.name}.`);
      setTimeout(() => setUploadSuccess(null), 5000);
    } catch (err: any) {
      setUploadError(err.message || 'Gagal mem-parsing file JSON.');
    } finally {
      if (jsonFileInputRef.current) jsonFileInputRef.current.value = '';
    }
  };

  // Reset current view session
  const resetSession = () => {
    if (confirm('Apakah Anda yakin ingin me-reset data tab ini?')) {
      if (activeTab === 'behavior') {
        setBehaviorPacks([]);
      } else if (activeTab === 'resource') {
        setResourcePacks([]);
      } else {
        setManifestName('My Custom Pack');
        setManifestDesc('Generated by BDSPack');
        setManifestType('behavior');
        setManifestUuid(generateUUID());
        setManifestModuleUuid(generateUUID());
        setManifestVersionStr('1.0.0');
        setMinEngineVersion('1.20.0');
      }
    }
  };

  return (
    <div className="flex-1 flex flex-col max-w-7xl w-full mx-auto p-4 md:p-6 space-y-6">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-border pb-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight flex items-center space-x-2">
            <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent font-sans">BDSPack</span>
            <span className="text-xs bg-muted border border-border px-2 py-0.5 rounded text-foreground/75 font-mono">v1.0</span>
          </h1>
          <p className="text-xs text-foreground/60 mt-1">
            Generate and manage Bedrock Dedicated Server addon configurations with ease.
          </p>
        </div>
        <ThemeToggle />
      </header>

      {/* Mode Selector and Setup */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <ModeToggle mode={mode} onChange={setMode} />
        
        {/* Quick info / Reset */}
        <div className="flex items-center space-x-2 justify-end">
          <button
            onClick={resetSession}
            className="flex items-center space-x-1 py-1.5 px-3 bg-muted hover:bg-black/5 dark:hover:bg-white/5 border border-border rounded-lg text-xs font-semibold cursor-pointer transition-colors"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Reset Tab</span>
          </button>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="border-b border-border flex space-x-4">
        <button
          onClick={() => setActiveTab('behavior')}
          className={`pb-2 text-sm font-semibold border-b-2 transition-all cursor-pointer ${
            activeTab === 'behavior'
              ? 'border-primary text-primary font-bold'
              : 'border-transparent text-foreground/60 hover:text-foreground'
          }`}
        >
          Behavior Packs
        </button>
        <button
          onClick={() => setActiveTab('resource')}
          className={`pb-2 text-sm font-semibold border-b-2 transition-all cursor-pointer ${
            activeTab === 'resource'
              ? 'border-secondary text-secondary font-bold'
              : 'border-transparent text-foreground/60 hover:text-foreground'
          }`}
        >
          Resource Packs
        </button>
        <button
          onClick={() => setActiveTab('manifest')}
          className={`pb-2 text-sm font-semibold border-b-2 transition-all cursor-pointer ${
            activeTab === 'manifest'
              ? 'border-primary text-primary font-bold'
              : 'border-transparent text-foreground/60 hover:text-foreground'
          }`}
        >
          Manifest Generator
        </button>
      </div>

      {/* Layout Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Column (Inputs, Lists, Configs) - 5 Cols */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* File Upload Panel */}
          {activeTab !== 'manifest' && (
            <div className="bg-muted/30 border border-border rounded-xl p-4 space-y-4">
              <h3 className="font-bold text-sm flex items-center space-x-2">
                <Upload className="w-4.5 h-4.5 text-primary" />
                <span>Upload & Import Addon</span>
              </h3>
              
              <div className="grid grid-cols-1 gap-3">
                {/* Mode B: Upload Existing JSON first */}
                {mode === 'B' && (
                  <div className="space-y-2">
                    <label className="text-xs font-semibold block">1. Muat JSON Server Lama</label>
                    <button
                      onClick={() => jsonFileInputRef.current?.click()}
                      className="w-full py-4 border border-dashed border-border rounded-xl flex flex-col items-center justify-center bg-background/50 hover:bg-background/80 transition-all cursor-pointer"
                    >
                      <FileJson className="w-8 h-8 text-foreground/45 mb-1.5" />
                      <span className="text-xs font-semibold text-foreground/80">Upload world_{activeTab}_packs.json</span>
                      <span className="text-[10px] text-foreground/50 mt-0.5">Parse file konfigurasi Anda yang sudah ada</span>
                    </button>
                    <input
                      ref={jsonFileInputRef}
                      type="file"
                      accept=".json"
                      onChange={handleJsonUpload}
                      className="hidden"
                    />
                  </div>
                )}

                {/* Upload Pack File (.mcpack / .mcaddon) */}
                <div className="space-y-2">
                  <label className="text-xs font-semibold block">
                    {mode === 'B' ? '2. Upload Addon Baru' : 'Upload Addon (.mcpack / .mcaddon)'}
                  </label>
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full py-4 border border-dashed border-border rounded-xl flex flex-col items-center justify-center bg-background/50 hover:bg-background/80 transition-all cursor-pointer"
                  >
                    <Upload className="w-8 h-8 text-primary/70 mb-1.5 animate-bounce" />
                    <span className="text-xs font-semibold text-foreground/80">Pilih file .mcpack / .mcaddon</span>
                    <span className="text-[10px] text-foreground/50 mt-0.5">Auto-extract metadata UUID dan Versi manifest</span>
                  </button>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".mcpack,.mcaddon,.zip"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                </div>
              </div>

              {/* Status notifications */}
              {uploadSuccess && (
                <div className="p-2.5 bg-green-500/10 border border-green-500/20 text-green-500 rounded-lg text-xs font-medium">
                  {uploadSuccess}
                </div>
              )}
              {uploadError && (
                <div className="p-2.5 bg-destructive/10 border border-destructive/20 text-destructive rounded-lg text-xs font-medium">
                  {uploadError}
                </div>
              )}
            </div>
          )}

          {/* Manifest Input Form (If Manifest Tab) */}
          {activeTab === 'manifest' && (
            <div className="bg-muted/30 border border-border rounded-xl p-4 space-y-4">
              <h3 className="font-bold text-sm flex items-center space-x-2">
                <FileJson className="w-4.5 h-4.5 text-primary" />
                <span>Konfigurasi Manifest Baru</span>
              </h3>

              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Tipe Pack</label>
                    <select
                      value={manifestType}
                      onChange={(e) => setManifestType(e.target.value as 'behavior' | 'resource')}
                      className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                    >
                      <option value="behavior">Behavior Pack (BP)</option>
                      <option value="resource">Resource Pack (RP)</option>
                    </select>
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Versi Addon</label>
                    <input
                      type="text"
                      value={manifestVersionStr}
                      onChange={(e) => setManifestVersionStr(e.target.value)}
                      placeholder="1.0.0"
                      className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                    />
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-semibold">Nama Addon</label>
                  <input
                    type="text"
                    value={manifestName}
                    onChange={(e) => setManifestName(e.target.value)}
                    placeholder="Nama addon..."
                    className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-semibold">Deskripsi</label>
                  <textarea
                    value={manifestDesc}
                    onChange={(e) => setManifestDesc(e.target.value)}
                    placeholder="Penjelasan addon..."
                    className="w-full h-16 bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50 resize-none"
                  />
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between items-center">
                    <label className="text-xs font-semibold">Pack UUID</label>
                    <button
                      onClick={() => setManifestUuid(generateUUID())}
                      className="text-[10px] text-primary hover:underline font-bold"
                    >
                      Acak UUID
                    </button>
                  </div>
                  <input
                    type="text"
                    value={manifestUuid}
                    onChange={(e) => setManifestUuid(e.target.value)}
                    className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs font-mono outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between items-center">
                    <label className="text-xs font-semibold">Module UUID</label>
                    <button
                      onClick={() => setManifestModuleUuid(generateUUID())}
                      className="text-[10px] text-primary hover:underline font-bold"
                    >
                      Acak UUID
                    </button>
                  </div>
                  <input
                    type="text"
                    value={manifestModuleUuid}
                    onChange={(e) => setManifestModuleUuid(e.target.value)}
                    className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs font-mono outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-semibold">Min Engine Version (Minecraft)</label>
                  <input
                    type="text"
                    value={minEngineVersion}
                    onChange={(e) => setMinEngineVersion(e.target.value)}
                    placeholder="1.20.0"
                    className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary/50"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Manual Entry Form (If Pack Tab) */}
          {activeTab !== 'manifest' && (
            <div className="bg-muted/30 border border-border rounded-xl p-4 space-y-4">
              <h3 className="font-bold text-sm flex items-center space-x-2">
                <Plus className="w-4.5 h-4.5 text-secondary" />
                <span>Tambah Entry Manual</span>
              </h3>

              <form onSubmit={handleAddManual} className="space-y-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Nama Pack Metadata (Opsional)</label>
                  <input
                    type="text"
                    value={manualName}
                    onChange={(e) => setManualName(e.target.value)}
                    placeholder="Nama pack (cth: Realism Shader)"
                    className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-secondary/50"
                  />
                </div>

                <div className="flex gap-3">
                  <div className="flex-1 space-y-1">
                    <div className="flex justify-between items-center">
                      <label className="text-xs font-semibold">Pack UUID</label>
                      <button
                        type="button"
                        onClick={generateManualUuid}
                        className="text-[10px] text-secondary hover:underline font-bold"
                      >
                        Acak
                      </button>
                    </div>
                    <input
                      type="text"
                      value={manualUuid}
                      onChange={(e) => setManualUuid(e.target.value)}
                      placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                      className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs font-mono outline-none focus:ring-1 focus:ring-secondary/50"
                    />
                  </div>
                  <div className="w-24 space-y-1">
                    <label className="text-xs font-semibold">Versi</label>
                    <input
                      type="text"
                      value={manualVersion}
                      onChange={(e) => setManualVersion(e.target.value)}
                      placeholder="1.0.0"
                      className="w-full bg-background border border-border rounded-md px-2.5 py-1.5 text-xs outline-none focus:ring-1 focus:ring-secondary/50"
                    />
                  </div>
                </div>

                <button
                  type="submit"
                  className="w-full py-2 bg-secondary text-black hover:bg-opacity-95 rounded-lg text-xs font-bold transition-all cursor-pointer shadow-md shadow-secondary/10"
                >
                  Tambah ke List
                </button>
              </form>
            </div>
          )}

          {/* Loaded Pack List */}
          {activeTab !== 'manifest' && (
            <div className="bg-muted/30 border border-border rounded-xl p-4 space-y-4">
              <h3 className="font-bold text-sm flex items-center justify-between">
                <span>Daftar Pack ({activeTab === 'behavior' ? behaviorPacks.length : resourcePacks.length})</span>
                <span className="text-[10px] text-foreground/50 font-normal">Reorder & Hapus</span>
              </h3>
              <PackList
                packs={activeTab === 'behavior' ? behaviorPacks : resourcePacks}
                type={activeTab}
                onReorder={handleReorder}
                onDelete={handleDelete}
              />
            </div>
          )}
        </div>

        {/* Right Column (Code Editor & Output Panel) - 7 Cols */}
        <div className="lg:col-span-7 space-y-6">
          {/* JSON Code Editor */}
          <div className="space-y-2">
            <div className="flex justify-between items-center text-xs">
              <span className="font-bold text-foreground/70 uppercase tracking-wider">
                {activeTab === 'manifest' ? 'Manifest Editor' : `world_${activeTab}_packs.json`}
              </span>
              <span className="text-foreground/45">Bisa diedit manual secara real-time</span>
            </div>
            
            <JsonEditor
              value={editorValue}
              onChange={handleEditorChange}
              isValid={isValidJson}
              onFormat={triggerPrettier}
              onGenerateUUID={activeTab === 'manifest' ? () => {
                setManifestUuid(generateUUID());
                setManifestModuleUuid(generateUUID());
              } : undefined}
            />
          </div>

          {/* AI Panel */}
          <AiPanel currentJson={editorValue} onAiResponse={handleEditorChange} />

          {/* Output Exporter / Download panel */}
          <OutputPanel
            jsonValue={editorValue}
            fileName={
              activeTab === 'manifest'
                ? 'manifest.json'
                : `world_${activeTab}_packs.json`
            }
            packs={activeTab === 'behavior' ? behaviorPacks : resourcePacks}
            showDiff={mode === 'B' && activeTab !== 'manifest'}
          />
        </div>

      </div>

      {/* BDS Guide / Info Footer */}
      <footer className="border-t border-border pt-6 pb-8 space-y-4 text-xs">
        <div className="bg-muted/20 border border-border p-4 rounded-xl space-y-2.5">
          <h4 className="font-bold flex items-center space-x-1.5 text-foreground/80">
            <BookOpen className="w-4.5 h-4.5 text-primary" />
            <span>Panduan Instalasi Addon Bedrock Dedicated Server (BDS)</span>
          </h4>
          <p className="text-foreground/60 leading-relaxed">
            Minecraft Bedrock Dedicated Server menggunakan file JSON untuk mengidentifikasi addon mana yang aktif di dunia game server Anda.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>1</span>
                <ChevronRight className="w-3 h-3" />
                <span>Upload Packs</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Copy folder behavior pack ke <code className="font-mono">/behavior_packs</code> dan resource pack ke <code className="font-mono">/resource_packs</code> di root folder BDS Anda.
              </p>
            </div>
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>2</span>
                <ChevronRight className="w-3 h-3" />
                <span>Generate JSON</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Gunakan BDSPack untuk me-list dan mengurutkan UUID & Versi pack Anda, lalu download file konfigurasinya.
              </p>
            </div>
            <div className="bg-muted/40 p-2.5 rounded-lg border border-border space-y-1">
              <div className="font-bold text-primary flex items-center space-x-1">
                <span>3</span>
                <ChevronRight className="w-3 h-3" />
                <span>Copy ke World</span>
              </div>
              <p className="text-foreground/50 text-[10px]">
                Letakkan file <code className="font-mono">world_behavior_packs.json</code> dan <code className="font-mono">world_resource_packs.json</code> di dalam folder level dunia Anda (cth: <code className="font-mono">/worlds/Bedrock level/</code>).
              </p>
            </div>
          </div>
        </div>

        <div className="text-center text-foreground/40 text-[10px]">
          BDSPack &copy; 2026. Minecraft Bedrock Dedicated Server Pack Configuration Utility.
        </div>
      </footer>
    </div>
  );
}
